[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Titouan"
authors = [{name = "Titouan", email = "t.heyrendt@gmail.com"}]
dynamic = ["version", "description"]
